### ISSUE TITLE
[Question] any differences with existing popular labelling bots for github?

### ISSUE THREAD

**Issue by orchestr7** [ansnadeem/aic#2]
There was an awesome and popular bot for labelling of issues:
https://github.com/marketplace/issue-label-bot

What is the differnce between your tool and those? 😄

**Comment by ansnadeem** [comment]
While we are aware that classification of issues is not novel, our take of the problem is novel.
Existing solutions tend to use key-word based models, which might end up giving false positives in case label related keywords are used, whereas we used a context-aware model which tend to do a better job since they understand the overall context.
Additionally, existing approaches treat the label prediction as a multi-class classification problem while our tool tends to identify incase one report falls into multiple categorizes by treating it as a multi-label problem since practically, a github issue allows users to label one report with more than just a single label. This is useful for example; in a case where a user might simultaneously want to report a bug as well as request an enhancement in the same report.

We document existing approaches and their limitations extensively in our article which is to appear in ISSRE 2021, moreover, we have an upcoming talk on our tool as well in the same conference. We look forward to the community reading our work on it, a link to the publication will be shared on the repository, as soon as it is published. We also intend to improve the documentation on this repository and the tool itself as soon our work is published :)
